/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIAssistantView: typeof import('./src/components/ai_assistant/AIAssistantView.vue')['default']
    Calendar: typeof import('./src/components/schedule_calendar/Calendar.vue')['default']
    Clock: typeof import('./src/components/login/compoents/Clock.vue')['default']
    Con1: typeof import('./src/components/Con1.vue')['default']
    Con2: typeof import('./src/components/Con2.vue')['default']
    Content: typeof import('./src/components/layout/Content.vue')['default']
    CourseManagerView: typeof import('./src/components/course_manager/CourseManagerView.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FriendsView: typeof import('./src/components/friends/FriendsView.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/home/index.vue')['default']
    HomeworkManagerView: typeof import('./src/components/homework_manager/HomeworkManagerView.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    Main: typeof import('./src/components/layout/Main.vue')['default']
    RegisterView: typeof import('./src/components/register/RegisterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./src/components/schedule_calendar/Schedule.vue')['default']
    ScheduleCalendarView: typeof import('./src/components/schedule_calendar/ScheduleCalendarView.vue')['default']
    SharedCalendarView: typeof import('./src/components/shared_calendar/SharedCalendarView.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TodoView: typeof import('./src/components/todo/TodoView.vue')['default']
  }
}
